// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGOtkRvHK0UtW6-hggL6SLWDW_5FfTns4',
    appId: '1:463636097061:web:0c9d7fc54351dda0b977cc',
    messagingSenderId: '463636097061',
    projectId: 'simple-crud-app-a57d7',
    authDomain: 'simple-crud-app-a57d7.firebaseapp.com',
    storageBucket: 'simple-crud-app-a57d7.firebasestorage.app',
    measurementId: 'G-VQ1XKXVB61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAgCYMWPj4qeHolcjdYz7795RDa1iRcOc',
    appId: '1:463636097061:android:3d25c89d073b7290b977cc',
    messagingSenderId: '463636097061',
    projectId: 'simple-crud-app-a57d7',
    storageBucket: 'simple-crud-app-a57d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC42-Yw0Sekyoc7lm70AhsSFRnWQvfFmVw',
    appId: '1:463636097061:ios:5bdcee9fcb1db7b3b977cc',
    messagingSenderId: '463636097061',
    projectId: 'simple-crud-app-a57d7',
    storageBucket: 'simple-crud-app-a57d7.firebasestorage.app',
    iosBundleId: 'com.riskee.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC42-Yw0Sekyoc7lm70AhsSFRnWQvfFmVw',
    appId: '1:463636097061:ios:5bdcee9fcb1db7b3b977cc',
    messagingSenderId: '463636097061',
    projectId: 'simple-crud-app-a57d7',
    storageBucket: 'simple-crud-app-a57d7.firebasestorage.app',
    iosBundleId: 'com.riskee.firebaseCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGOtkRvHK0UtW6-hggL6SLWDW_5FfTns4',
    appId: '1:463636097061:web:ef96f22c6ac1af1ab977cc',
    messagingSenderId: '463636097061',
    projectId: 'simple-crud-app-a57d7',
    authDomain: 'simple-crud-app-a57d7.firebaseapp.com',
    storageBucket: 'simple-crud-app-a57d7.firebasestorage.app',
    measurementId: 'G-3XFPN32GWE',
  );
}
